
### NOTES
GET http://localhost:3000/api/notes

GET http://localhost:3000/api/notes?q=Node

GET http://localhost:3000/api/notes?tag=work

POST http://localhost:3000/api/notes
Content-Type: application/json

{ "title": "Nowa notatka", "body": "Treść nowej notatki o pracy i domu." }

### TAGS
GET http://localhost:3000/api/tags

POST http://localhost:3000/api/notes/1/tags
Content-Type: application/json

{ "tags": ["work", "home"] }
