services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ti-lab03-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Course__Name: Technologie Internetowe
