-- 01_schema.sql
-- Tworzenie bazy i tabel dla zestawu 6 zadań (SQL Server 2019/2022/Express)

IF DB_ID('DemoDB') IS NULL
BEGIN
  CREATE DATABASE DemoDB;
END
GO

ALTER DATABASE DemoDB SET RECOVERY SIMPLE;
GO

USE DemoDB;
GO

-- USERS
IF OBJECT_ID('dbo.Users','U') IS NULL
CREATE TABLE dbo.Users(
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Username NVARCHAR(100) NOT NULL UNIQUE,
  Email NVARCHAR(200) NOT NULL UNIQUE,
  PasswordHash VARBINARY(256) NULL,
  PasswordSalt VARBINARY(128) NULL,
  LastLoginAt DATETIME2 NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);
GO

-- REFRESH TOKENS
IF OBJECT_ID('dbo.RefreshTokens','U') IS NULL
CREATE TABLE dbo.RefreshTokens(
  Id INT IDENTITY(1,1) PRIMARY KEY,
  UserId INT NOT NULL REFERENCES dbo.Users(Id) ON DELETE CASCADE,
  Token NVARCHAR(500) NOT NULL,
  ExpiresAt DATETIME2 NOT NULL,
  RevokedAt DATETIME2 NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);
GO

-- TASKS
IF OBJECT_ID('dbo.Tasks','U') IS NULL
CREATE TABLE dbo.Tasks(
  TaskId INT IDENTITY(1,1) PRIMARY KEY,
  UserId INT NOT NULL REFERENCES dbo.Users(Id) ON DELETE CASCADE,
  Title NVARCHAR(200) NOT NULL,
  IsDone BIT NOT NULL DEFAULT 0,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);
GO

-- AUDIT LOG
IF OBJECT_ID('dbo.AuditLog','U') IS NULL
CREATE TABLE dbo.AuditLog(
  LogId INT IDENTITY(1,1) PRIMARY KEY,
  UserId INT NULL,
  Action NVARCHAR(100) NOT NULL,
  RefId INT NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);
GO

-- STAGING
IF OBJECT_ID('dbo.Users_Staging','U') IS NULL
CREATE TABLE dbo.Users_Staging(
  Username NVARCHAR(100) NOT NULL,
  Email NVARCHAR(200) NOT NULL,
  ImportedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);
GO
