server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    add_header X-Lab "TI-01" always;

    location / {
        try_files $uri $uri/ =404;
    }

    location = /old {
        return 302 /about.html;
    }
}
